services:
  # For database
  db:
    image: postgres:15-alpine
    container_name: carworkshop-psql
    restart: always
    environment:
      POSTGRES_DB:  ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - carworkshop_data:/var/lib/postgresql/data
    networks:
      - app-network

  # For Backend
  backend:
    build: ./Backend
    container_name: carworkshop-api
    restart: always
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: "car-workshop-api"
      Jwt__Audience: "car-workshop-frontend"
    depends_on:
      - db
    networks:
      - app-network

  # For Frontend
  frontend_proxy:
    build: ./Frontend
    container_name: carworkshop-nginx
    restart: always
    ports:
      - "80:80"   # For HTTP - docker_port:nginx_port 
      # - "443:443" # For Https - enable it for prod 
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  carworkshop_data: